export const STEPS = [
  {
    id: 1,
    title: 'What is a Force Vector?',
    lead: 'A force has two properties: magnitude (how strong) and direction (which way). The red arrow represents a force — its length shows strength, its angle shows direction.',
    hint: 'Drag the angle slider from 0° to 90° (or grab the arrowhead in the diagram) and watch the arrow rotate. Hold Shift + arrow key for 0.5° steps.',
    guidance: null,
    controls: ['magnitude', 'angle'],
    scene: new Set(['grid', 'axes', 'forceVector', 'forceLabel', 'angleArc', 'angleLabel']),
    showEquations: false,
    whatYouSee: 'The red arrow is the force vector. Its length represents the magnitude (strength in Newtons). The angle θ, measured counterclockwise from the X-axis, sets the direction.',
    realWorld: 'Think of a rope pulling a heavy block. The tension in the rope is the magnitude. The direction the rope points is the angle θ.',
    conceptCheck: null,
    insight: false,
  },
  {
    id: 2,
    title: 'Horizontal Effect of the Force',
    lead: 'Part of the force acts horizontally — pushing left or right. This horizontal portion is called the X-component, written as Fx.',
    hint: 'At θ = 0°, all force acts horizontally — Fx equals the full force F. At θ = 90°, the horizontal push drops to zero.',
    guidance: null,
    controls: ['magnitude', 'angle'],
    scene: new Set(['grid', 'axes', 'forceVector', 'forceLabel', 'angleArc', 'angleLabel', 'fxOnly']),
    showEquations: false,
    whatYouSee: 'The teal dashed arrow shows only Fx — the horizontal component. The original red force is also shown for reference. Notice how Fx shrinks as the angle increases toward 90°.',
    realWorld: 'Pushing a lawn mower at an angle: only part of your effort moves it forward. That forward push is Fx — the horizontal component of the applied force.',
    conceptCheck: {
      question: 'What happens to Fx when θ increases from 0° to 90°?',
      options: [
        { text: 'Fx increases', correct: false },
        { text: 'Fx decreases to zero', correct: true },
        { text: 'Fx stays the same', correct: false },
      ],
      explanation: 'As θ increases toward 90°, the force turns more vertical — so the horizontal push (Fx) gradually shrinks to zero. Try setting θ to 90° and watch Fx disappear.',
    },
    insight: false,
  },
  {
    id: 3,
    title: 'Vertical Effect of the Force',
    lead: 'Part of the force also acts vertically — pushing up or down. This vertical portion is called the Y-component, written as Fy.',
    hint: 'At θ = 90°, all force acts vertically — Fy equals F. At θ = 0°, there is no vertical effect at all.',
    guidance: null,
    controls: ['magnitude', 'angle'],
    scene: new Set(['grid', 'axes', 'forceVector', 'forceLabel', 'angleArc', 'angleLabel', 'fyOnly']),
    showEquations: false,
    whatYouSee: 'The amber dashed arrow shows only Fy — the vertical component. As the angle increases, the force tilts more upward and Fy grows. At θ = 90°, Fy equals the full force F.',
    realWorld: 'A crane cable lifting a load: the vertical part of the cable tension does the actual lifting. That upward pull is Fy — the vertical component.',
    conceptCheck: {
      question: 'What happens to Fy when θ increases from 0° to 90°?',
      options: [
        { text: 'Fy increases', correct: true },
        { text: 'Fy decreases', correct: false },
        { text: 'Fy stays the same', correct: false },
      ],
      explanation: 'As θ increases toward 90°, the force tilts more vertically — so the vertical component (Fy) grows larger. At θ = 90°, Fy equals the full magnitude F.',
    },
    insight: false,
  },
  {
    id: 4,
    title: 'Resolving the Force',
    lead: 'Any angled force can be replaced by two perpendicular components — Fx and Fy. Together, they produce exactly the same effect as the original force. This is called vector resolution.',
    hint: 'Fx = F cos θ   •   Fy = F sin θ',
    guidance: 'The right-angle marker at the corner confirms Fx and Fy meet at exactly 90°. The three arrows form a right triangle — the foundation of vector resolution.',
    controls: ['magnitude', 'angle'],
    scene: new Set(['grid', 'axes', 'forceVector', 'forceLabel', 'angleArc', 'angleLabel', 'components']),
    showEquations: true,
    whatYouSee: 'Fx (teal) and Fy (amber) now appear together. The right-angle marker at their corner confirms 90°. The original force is equivalent to Fx and Fy acting simultaneously — they form a right triangle.',
    realWorld: null,
    conceptCheck: null,
    insight: false,
  },
  {
    id: 5,
    title: 'Explore and Build Intuition',
    lead: 'Now explore freely. Drag the sliders and observe how Fx and Fy respond to angle changes. The insight panel will update automatically as you explore.',
    hint: 'Try θ = 30°, 45°, and 60°. Notice how the balance between Fx and Fy shifts with each angle.',
    guidance: null,
    controls: ['magnitude', 'angle'],
    scene: new Set(['grid', 'axes', 'forceVector', 'forceLabel', 'angleArc', 'angleLabel', 'components']),
    showEquations: true,
    whatYouSee: null,
    realWorld: null,
    conceptCheck: null,
    insight: true,
  },
];

export const TOTAL_STEPS = STEPS.length;
